# Generated by Django 5.0.6 on 2024-12-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedbook',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuedbook',
            name='status',
            field=models.CharField(choices=[('Issued', 'Issued'), ('Returned', 'Returned')], default='Issued', max_length=10),
        ),
    ]
