# Generated by Django 5.0.6 on 2024-12-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_issuedbook_return_date_issuedbook_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='book_covers/'),
        ),
    ]
